### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by TheSuperGamer20578** [TheSuperGamer20578/EMC-info#1]
on PyPI the links and linebreak in the description are non-existant

**Comment by aitc-h** [comment]
Looks like this might be related to https://github.com/pypa/setuptools/issues/1390. You'll need to take a look at your PKG_INFO to make sure though. There are a few fixes discussed on the thread

**Comment by TheSuperGamer20578** [comment]
The issue has been fixed I just needed to update a few things
[![image](https://user-images.githubusercontent.com/30369708/89979225-93ca0080-dcb2-11ea-8aeb-e01f2bd7dc81.png)](https://packaging.python.org/guides/making-a-pypi-friendly-readme/)
